shared:
  image: maven:3-adoptopenjdk-8

jobs:
  pr:
    steps:
      - run_arbitrary_script: mvn clean test --quiet
  main:
    requires: [~pr, ~commit]
    steps:
      - run_arbitrary_script: mvn clean test --quiet
